### ISSUE TITLE
Creating annotations on pdf.js with javascript

### ISSUE THREAD

**Issue by sanjivani2208** [mzabriskie/pdf-annotate.js#2]
I want to annotate pdf using pdf.js. Is there any solution for this as I am not using node.js

**Comment by mzabriskie** [comment]
Sorry for the delay, I just noticed your comment.

This library is meant to add annotation support for pdf.js. It requires that you implement your own backend to handle all the CRUD operations for annotations. This library doesn't prescribe what your backend language is, so long as it can receive and provide the proper JSON format of annotation data. Once you have a backend you will need to implement `PDFJSAnnotate.StoreAdapter` methods so that this library knows how to communicate with your backend.

Currently this library is still a work in progress. It is close to being ready for use, but has not been published to npm.

**Comment by chitgoks** [comment]
Check out this video. It does just that.
https://www.youtube.com/watch?v=agrBJH1TriI

**Comment by kishandonepudi** [comment]
I want to use annotate pdf over pdf.js , i'm using node.

Please help me
